### ISSUE TITLE
Resize window in Menu

### ISSUE THREAD

**Issue by Noixas** [Noixas/CrazyPutting#1]
The button location doesn't changes in menu when resizing the screen

**Comment by sugonkong** [comment]
I have a question in the algorithm in 3D-KP
 I want to know the greedy algorithm in Outline and Keywords.
 There is currently an error and the file is not working.
 Thank you.
 Contact tnrhs0420@naver.com
 please
 /////
 Ik heb een vraag in het algoritme.
 Ik wil het hebzuchtige algoritme in overzicht en trefwoorden kennen.
 Er is momenteel een fout opgetreden en het bestand werkt niet.
 Bedankt.
 Neem contact op met tnrhs0420@naver.com
 alsjeblieft
